/*

 KEYBOARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\riley\Desktop\gbtd22\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define keyboardWidth 20
#define keyboardHeight 18
#define keyboardBank 0

extern unsigned char keyboard[];

/* End of KEYBOARD.H */
